require 'rack/oauth2'

class FacebooksController < ApplicationController
  before_filter :require_authentication, :only => :destroy

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    auth = Facebook.auth.from_cookie(cookies)
    authenticate Facebook.identify(auth.user)
    redirect_to dashboard_url
  end

  # handle Normal OAuth flow: start
  def new
    redirect_to client.authorization_uri(
      :scope => Facebook.config[:perms]
    )
  end

  # handle Normal OAuth flow: callback
  def create
    client.authorization_code = params[:code]
    access_token = client.access_token![:access_token]
    user = FbGraph::User.me(access_token).fetch
    authenticate Facebook.identify(user)
    redirect_to dashboard_url
  end

  def destroy
    unauthenticate
    redirect_to root_url
  end

  private

  def client
    @client ||= Rack::OAuth2::Client.new(
      :identifier => Facebook.config[:client_id],
      :secret => Facebook.config[:client_secret],
      :redirect_uri => callback_facebook_url,
      :authorization_endpoint => 'https://www.facebook.com/dialog/oauth',
      :token_endpoint => 'https://graph.facebook.com/oauth/access_token'
    )
  end

end
